export enum GameEvent {
  startBallThrow = 'startBallThrow',
  dragBall = 'dragBall',
  releaseBallThrow = 'releaseBallThrow',
  gameOver = 'gameOver',
  terminate = 'terminate',
  play = 'play',
  replay = 'replay',
  fallInHole = 'fallInHole',
  gameStateChange = 'gameStateChange',
  batteryChange = 'batteryChange',
  dischargeComplete = 'dischargeComplete',
  discharge = 'discharge',
  dischargePreview = 'dischargePreview',
  dischargeDismissPreview = 'dischargeDismissPreview',
  puckKilled = 'puckKilled',
  resize = 'resize',
  fullscreen = 'fullscreen',
}
