export enum GameEvent {
  startBallThrow = "startBallThrow",
  dragBall = "dragBall",
  releaseBallThrow = "releaseBallThrow",
  goal = "goal",
  gameOver = "gameOver",
  destroyAll = "destroyAll",
  timesUp = "timesUp",
  finalShotScored = "finalShotScored",
  replay = "replay",
  cleanHit = "cleanHit",
  home = "home",
  pickupTaken = "pickupTaken",
  gameStateChange = "gameStateChange",
  terminate = "terminate",
  play = "play",
}
